### ISSUE TITLE
CLA cannot be signed or agreed to

### ISSUE THREAD

**Issue by earlruby** [vmware-ai-labs/vm-packer-for-ray#12]
The `CONTRIBUTING_CLA.md` file states that "Before you start working with vm-packer-for-ray, please read and sign our Contributor License Agreement [CLA](https://cla.vmware.com/cla/1/preview)."

The [CLA](https://cla.vmware.com/cla/1/preview) displays a page that you can read, but there's no way to actually sign it or agree to the terms.

**Comment by JingChen23** [comment]
If you are an employee of VMware then you don't need to sign CLA, you just need to be a member of the organization.

Check the page below:

![Screenshot 2023-10-16 at 09 28 45](https://github.com/vmware-ai-labs/vm-packer-for-ray/assets/15973672/462dbaec-c1e0-4966-8cb3-74c7edd5ad5b)

Also, I'm going to investigate if contributors outside VMware will also face the same issue.
